language: node_js
node_js:
  - "10.16.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install
script:
  - echo "begin run yarn install"
  - yarn test:unit
  - echo unit test pass
#  - cache:
#      yarn: true
#before_install:
#  - openssl aes-256-cbc -K $encrypted_830d3b21a25d_key -iv $encrypted_830d3b21a25d_iv
#    -in id_rsa.enc -out ~/.ssh/id_rsa -d
#  - chmod 600 ~/.ssh/id_rsa
#  - echo -e "Host 102.201.64.94\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#deploy:
#  provider: pages
#  skip_cleanup: true
#  # github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
after_success:
  echo "build success"
#  - npm prune --production  # 删除devDependencies
#  - tar -jcf indoor-server.tar.bz2 *    # 打包并压缩代码
#  - scp indoor-server.tar.bz2 jingsam@102.201.64.94:~/  # 复制到生产服务器上
#  - ssh jingsam@102.201.64.94 'mkdir -p indoor-server && tar -jxf indoor-server.tar.bz2 -C indoor-server'   # 解压
#  - ssh jingsam@102.201.64.94 'cd indoor-server && pm2 startOrReload pm2.json'  # 重启pm2
